### ISSUE TITLE
relicense under gplv2

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#100]
Relicense COAL under GPLv2 for compatibility with Spectral Python as discussed [on GitHub](https://github.com/conda-forge/staged-recipes/pull/3002#pullrequestreview-42210229) and [on the mailing list](https://groups.google.com/forum/#!topic/coal-capstone/GcunRNllPLs).

All COAL developers (copyright holders) have agreed to this change.

The documentation and website will need to be updated as well.

**Comment by ghost** [comment]
@lewismc the website and documentation will still need to be updated, but this could be tracked in another issue. once finals week is over i could take care of it.

**Comment by lewismc** [comment]
I'll do it today, if you could point me to exactly where the edits need to be then I'll do them.

**Comment by lewismc** [comment]
Will address subsequent relicensing in another issue.

**Comment by ghost** [comment]
Sorry about the delay, I had some grueling AI homework to take care of yesterday so I wasn't online. Doing something like `grep -Ri apache *` in each of our repositories would probably be enough to find each instance. We're working on the final report now so when that's done I can address the changes and submit a pull.
