### ISSUE TITLE
Address Landscape.io issues in pycoal/environment.py

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#103]
https://landscape.io/github/capstone-coal/pycoal/53/modules/pycoal/environment.py#L19

Also touches environment_test.py

**Comment by ghost** [comment]
lol, i guess landscape doesn't like camelCase? i guess i missed that part when i was reading the python dogma.

i didn't have a chance to look closely at the changes, but assuming no typos were introduced and all the tests continue to pass, there shouldn't be any functional effect. i assume the other files should be edited similarly for consistency.

**Comment by ghost** [comment]
We may also need to update the website documentation to account for any interfaces that were changed by this reformatting.

**Comment by lewismc** [comment]
Ack
Wil do incrementally

**Comment by lewismc** [comment]
I've updated the [usage](https://capstone-coal.github.io/docs#usage) on the Website in anticipation for the API changes.

**Comment by ghost** [comment]
Confirming that this is still an open issue.

**Comment by lewismc** [comment]
Yes

**Comment by lewismc** [comment]
Landscape no longer exists... closing off.
