### ISSUE TITLE
Implement REST API with the Falcon Web Framework

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#109]
It would be very handy if task execution could be run remotely. In order to do this we can use a framework such as [Falcon](https://falcon.readthedocs.io/en/stable/).

**Comment by lewismc** [comment]
I'm currently working on this and will be finished soon.

**Comment by bdegley4789** [comment]
Is this still an open issue? And could this be a task for @thomkenn to work on if you are not already done?  I built a very basic REST API in my cloud and mobile development course on the google cloud platform in about one week. For something more complicated like task execution of pycoal it would take longer but definitely achievable before capstone

**Comment by thomkenn** [comment]
yeah i can definitly take this one up, but im concerned the REST API might rely on the SDS part of it, in which case obviously this would no longer be within our scope. if im reading that wrong, let me know

**Comment by lewismc** [comment]
@thomkenn 

> ...but im concerned the REST API might rely on the SDS part of it

Yes it does.
