### ISSUE TITLE
Create examples directory with example scripts

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#111]
Based on the [toolkit usage documentation](https://capstone-coal.github.io/docs#usage) we should create an examples directory and three simple scripts which augment the usage with CLI invocation enabling end-to-end COAL execution. This will make it much easier for people to run the toolkit from examples.

**Comment by lewismc** [comment]
@browtayl can you point me to the location of the [National Hydrography Dataset National Map shape files](https://capstone-coal.github.io/docs#environment) which are required in order to complete the environmental portion of the example? I've been looking over at the USGS Website but cannot find a link to ```NHDNM/Shape/NHDFlowline.shp``` thank you in advance.

**Comment by lewismc** [comment]
It's cool @browtayl I found them at ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Hydrography/NHD/State/HighResolution/Shape/ thanks

**Comment by lewismc** [comment]
The shape files can be located at ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/Hydrography/NHD/State/HighResolution/Shape/NHD_H_New_Mexico_Shape.zip thanks

**Comment by ghost** [comment]
For reference here is the email thread where I originally found it:
https://groups.google.com/forum/#!topic/coal-capstone/MBVIBZBc_cs

Here is its catalog page which we will want to cite:
https://www.sciencebase.gov/catalog/item/58c9238ce4b0849ce97b41b1

[Note](https://github.com/capstone-coal/pycoal/issues/20#issuecomment-294290644) that some builds of GDAL might not include FileGDB support.
