### ISSUE TITLE
Fix GDAL Bug Fix

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#117]
Several [flaws](https://github.com/OSGeo/gdal/pull/197#issuecomment-316185610) were found in the original GDAL ENVI rotation bug [fix](
https://capstone-coal.github.io/2017/04/30/gdal-envi-rotation-bug-fix.html). I [confirmed](https://lists.osgeo.org/pipermail/gdal-dev/2017-July/046877.html) the errors, but the reporter has not delivered a patch as was suggested. The reporter proposed corrected equations, however it will be necessary to review the coordinate system and linear algebra to verify them. This issue is to follow up and patch the patch as time allows. I do not believe this issue currently affects COAL because of symmetry in the AVIRIS imagery we are using.

**Comment by lewismc** [comment]
@browtayl can you please look into this again and see if 
 1) the reporter delivered a patch as was suggested, and 
 2) if so, has the fix made it into a packaged version of GDAL?
I am looking to simplify the [GDAL install in the Dockerfile](https://github.com/capstone-coal/pycoal/blob/master/Dockerfile#L75-L140) if possible... it would be ultimately easier to grab a Debian package or something similar if available.

Thanks

**Comment by ghost** [comment]
To my knowledge, the reporter did not deliver a patch. When I have time I will follow up on the changes they suggested. Note that the original fix is sufficient for our purposes, it was only in a special case (when pixel x and y dimensions differ) that the symmetry fails. My original fix was incorporated into the officially released version of GDAL 2.2.0, but the [current version in Debian Stable](https://packages.debian.org/stretch/libgdal-dev) is 2.1.2, although 2.2.3 appears to be in Testing. My recommendation would be to use CheckInstall to build a Debian package yourself [as described in the ~blog~ docs](https://capstone-coal.github.io/docs#gdal).

**Comment by ghost** [comment]
Alternately, it is possible the Debian package in Testing will run on Stable. I don't see it in Backports.

**Comment by ghost** [comment]
I will add to this stream of consciousness by noting that GDAL originally had no support for rotated ENVI files at all, so my original fix didn't break anything that previously worked. Fixing the symmetry would presumably enable full compatibility with the (undocumented and proprietary) ENVI header format. To my knowledge all AVIRIS-C and AVIRIS-NG data has |x|==|y| so it is presently a non-issue for our purposes.

I am not that familiar with Docker, but if you can include binaries such as a `.deb` file, you could automate installation with `sudo dpkg -i gdal_package_name.deb`. Of course there are more elegant ways of building a `.deb` file then CheckInstall. It may be necessary to consider the source and target architectures for the Docker build, although our use case seems to be limited to `x86_64` at present.

Once the original fix is fixed, it will take an indeterminate amount of time for it to be 1) merged into GDAL and 2) packaged in a distribution. This is the double-edged sword of using a distro as stable as Debian. Something like Fedora or Ubuntu might have newer packages, but then you have to worry about the whole system breaking on each update, which is why I prefer to maintain the handful of packages I need newer versions of.

**Comment by ghost** [comment]
Forgot to mention it, there actually is a GDAL `.deb` package generated during the first R&D phase: In the COAL Google Drive > `coal-capstone` > `2016-2017` > `software`. However it was built for Debian 8 so it might not be compatible with Debian 9.

**Comment by bdegley4789** [comment]
@browtayl Has this issue been address with what we did in Follow Up on Improving GDAL/QGIS Installation Instructions ?

**Comment by ghost** [comment]
@bdegley4789 Negative, this issue is to submit a new patch to the GDAL source itself: https://lists.osgeo.org/pipermail/gdal-dev/2017-July/046877.html . The original fix works if pixel x and y dimensions are equal but breaks otherwise. The individual who reported this on the GDAL mailing list said they would provide a patch but hasn't gotten around to it. I have been planning on revisiting it myself, but there is some slightly complicated algebra I haven't had the time to work through. I'm sure you know the feeling, so thanks for checking in on this.

**Comment by ghost** [comment]
GDAL has transitioned its issue tracker to GitHub. This issue should be addressed there.
