### ISSUE TITLE
design document revision

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#12]
Address revisions to the design document noted after approval of initial draft in pull request https://github.com/capstone-coal/coal/pull/9.

**Comment by lewismc** [comment]
Is this complete

**Comment by lewismc** [comment]
@browtayl ping

**Comment by ghost** [comment]
Sorry, @lewismc, your previous comment got past me. The issue is currently unresolved. According to Heidi, it looks like we're due to revise this and the other documents on the 17th.

**Comment by lewismc** [comment]
ok doke

**Comment by ghost** [comment]
@heidiaclayton @xiaomei7 We can refer to the comments in the [Design draft](https://github.com/capstone-coal/coal/pull/9) pull request when we revise the document. Note that there are also comments to address for the [tech review](https://github.com/capstone-coal/coal/pull/8).

**Comment by ghost** [comment]
Here's info on citing GDAL if we need it:
http://trac.osgeo.org/gdal/wiki/FAQGeneral#HowdoIciteGDAL

**Comment by ghost** [comment]
closing this issue as changes will be implemented along with the rest of our [winter midterm](https://github.com/capstone-coal/coal/issues/28).
