### ISSUE TITLE
Classifier Callback

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#122]
This issue is to implement the functionality requested in https://github.com/capstone-coal/capstone-coal.github.io/issues/32 to allow the user to control the classification algorithm. One option is to refactor the mineral classification method to take a callback which defaults to the current SAM implementation. Additional work remains to figure out the best way to do this.

**Comment by thomkenn** [comment]
This could be interesting, ill take a look at it

**Comment by lewismc** [comment]
@thomkenn please begin thinking about implementing this. I already have [other work lined up to expand the Classification algorithms](https://github.com/ESIPFed/GSoC/issues/10) for pycoal which would leverage this functionality. 
Any question, please post them here.

**Comment by thomkenn** [comment]
Am currently testing code on my local machine, will submit a pull request when i have it working.

**Comment by lewismc** [comment]
Hi @thomkenn you've been cranking on this now since your original interest on January 18th, 2018. Do you have a pull request?

**Comment by thomkenn** [comment]
ok i sent in a pull request with the tentative formatting i had in mind for this to work. Further documentation study and changing references to the mineral.py throughout the greater program will be required and updated after this is completed

**Comment by lewismc** [comment]
See my comment on the PR, close the PR and make sure your PR only includes
proposed changes not en entire history of the project.
Thanks

**Comment by thomkenn** [comment]
Apologies, i had github improperly configured, i went off the notes you gave on my last PR and i believe i have submitted the proper form

**Comment by lewismc** [comment]
@EvandroCT can you please start working on this issue to get yourself familiarized with the project source code? Thank you

**Comment by EvandroCT** [comment]
PR moved to https://github.com/capstone-coal/pycoal/pull/155

**Comment by EvandroCT** [comment]
Hey folks, please, take a look at my PR https://github.com/capstone-coal/pycoal/pull/155

**Comment by lewismc** [comment]
Thank you @EvandroCT
