### ISSUE TITLE
Create CLI and enable upon install

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#126]
mineral.py, mining.py and environment.py should each have a CLI. Upon successful installation of pycoal, the CLI tools should be available on the path for easy execution.

An example of how we did this elsewhere can be seen at the [pycovjson cli](https://github.com/Reading-eScience-Centre/pycovjson/tree/master/pycovjson/cli) module.

Really, the ```main``` function of our existing [examples](https://github.com/capstone-coal/pycoal/tree/master/examples) should really be extracted from the examples and moved to a new ```cli``` module. 

Additionally, in order to enable execution of these CLI upon install, we need to add the following code to the ```setup.py```
```
...
_zip_safe = False
_entry_points = {'console_scripts' : ['pycoal-mineral = pycoal.cli.mineral:main', 'pycoal-mining = pycoal.cli.mining:main', 'pycoal-environment = pycoal.cli.environment:main']}
```
we then need to append the variable to ```setup.py```'s _setup_ dictionary as follows
```
...
zip_safe=_zip_safe,
_entry_points = entry_points
```

**Comment by lewismc** [comment]
@bdegley4789 how is this going?

**Comment by bdegley4789** [comment]
@lewismc this issue is going alright. I have tried following the example you gave from pycovjson. I'm probably getting things wrong but I pushed the changed I've worked on to my [branch](https://github.com/bdegley4789/pycoal/tree/Issue-126/examples/cli)
Am I correct in thinking that I would put all the Command Line Options into the .py scripts in the CLI repo and then remove them from the .py scripts in the example directory?

**Comment by lewismc** [comment]
OK, these are the steps to address the task

1. add entries (as I previously described) to setup.py which expose the ```_entry_points```, this is so that upon installation, these tools are available via the CLI,
1. create a ```cli``` directory within the existing [pycoal](https://github.com/capstone-coal/pycoal/tree/master/pycoal) source directory. This will be used to house the ```_entry_points``` you've defined in 1 above
1. create the ```_entry_points``` e.g. pycoal.cli.mineral, pycoal.cli.mining and pycoal.cli.environment within the new [pycoal](https://github.com/capstone-coal/pycoal/tree/master/pycoal)/cli directory created in 2 above,
1. ensure that pycoal.cli.mineral, pycoal.cli.mining and pycoal.cli.environment files contain main methods which provide a CLI. Examples of how to do this are provided within the existing [examples](https://github.com/capstone-coal/pycoal/tree/master/examples) already. This is literally a copy and paste job.

Does the above make sense? This is not a complex task, so please tell me if I am not explaining it correctly. Thanks
