### ISSUE TITLE
Update Copyrights and Contributors

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#135]
This issue is to identify and update the copyright and contributor notices throughout the COAL software suite. There is considerable inconsistency in attribution between files, so I recommend we use a standard format like `Copyright (C) 2017-2018 COAL Contributors`.

I suggest we use the website [Team](https://capstone-coal.github.io/team) page as our definitive contributor list for the time being. There has been [at least one commit](https://github.com/capstone-coal/pycoal/commits?author=jarifibrahim) from outside the team so we might link to GitHub's [contributors](https://github.com/capstone-coal/pycoal/graphs/contributor) graphs to include every committer.

* I will update the **website** and provide a reference the relevant issue or pull request.
* As I commented in commit [`182be67`](https://github.com/capstone-coal/pycoal/commit/182be67115dd26aa1db499f8686317e70300257b), the copyright dates should be updated in the **`pycoal`** source.
* There is a typo in the "Author" field on [**PyPI**](https://pypi.python.org/pypi/pycoal). Recommend @lewismc amend to "COAL Contributors".
* The Sphinx [**docs**](https://pycoal.readthedocs.io/en/latest/) also contain a copyright notice which is somewhere in the `pycoal` source.

This is a partial list and I haven't looked at the SDS, etc. We probably don't need to worry about the conference poster or either teams' course documents.

Assigning to @lewismc and myself.

**Comment by lewismc** [comment]
# 2 has been addressed
# 3 has been addressed
# 4 has been addressed

**Comment by ghost** [comment]
Pull https://github.com/capstone-coal/pycoal/pull/137 hopefully fixes the remaining inconsistencies. The format for current and future copyright notices should be `Copyright (C) 2017-2018 COAL Developers` unless decided otherwise. I will update the website to refer to "Developers" rather than "Contributors" for uniformity. PyPI and RTD may not display the change until a new release.

**Comment by ghost** [comment]
Since we're playing fast and loose with the source these days I'm just going to merge and close. Reopen if anything is amiss.

**Comment by ghost** [comment]
Merged https://github.com/capstone-coal/pycoal/pull/137. Merged https://github.com/capstone-coal/capstone-coal.github.io/pull/50. Closed.
