### ISSUE TITLE
Purge Wiki

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#136]
This issue is to purge the [`pycoal` wiki](https://github.com/capstone-coal/pycoal/wiki) of obsolete documentation. Nobody needs to be reading the 2016-2017 team updates anymore which are in our final report anyways. I already deleted my FOSS page which was never particularly relevant. We could even consider getting rid of the wiki altogether and move all documentation to the website.

**Comment by thomkenn** [comment]
How about we just replace the 2016-2017 team updates page with a link to the 2016-2017 final report then? Sound good to everyone?

**Comment by ghost** [comment]
Done.
