### ISSUE TITLE
AttributeError: 'module' object has no attribute 'mineral'

### ISSUE THREAD

**Issue by BlcaKHat** [capstone-coal/pycoal#143]
I was running the example with one hyperspectral image having 20 bands. i got this error. But It generates 2 images. but they are not RGB or classified.

**Comment by bdegley4789** [comment]
@BlcaKHat We will look into this. Just to verify, you have built pycoal, correct?

python setup.py install

**Comment by BlcaKHat** [comment]
I installed it via pip. do i still need to build ?

**Comment by bdegley4789** [comment]
@BlcaKHat Yes you do, let me know how pycoal behaves after you have built

**Comment by BlcaKHat** [comment]
still got this error in 
# generate a mining classified image
mining_classification.classify_image(mineral_filename, mining_filename)

![last_line](https://user-images.githubusercontent.com/16970999/38917765-522a6cf4-4309-11e8-91a2-720280f0dce0.png)

I have aviris data of Ahamdabad , india and i have 9 classes . like ubran, water .. etc 
help me out.

**Comment by bdegley4789** [comment]
@BlcaKHat  It looks like you don't have spectral installed. Try

sudo pip install spectral

Here are all the dependencies for pycoal
https://capstone-coal.github.io/docs#dependencies

gdal will take a bit longer to install than the others but you won't need it until you try to generate an environmental classified file

**Comment by lewismc** [comment]
@BlcaKHat just do he following https://github.com/capstone-coal/pycoal#source

**Comment by lewismc** [comment]
@BlcaKHat please provide a link to the Ahamdabad imagery you are attempting to classify. Thanks

**Comment by BlcaKHat** [comment]
The data i am using is not Free or sharable in my country. I am working under ( Indian institute of Remote sensing ). I am not allowed to take the data. I will try to give you the details of data tommorow.

**Comment by BlcaKHat** [comment]
I have installed spectral and I was working with spectral to work with hyperspectral data

**Comment by lewismc** [comment]
@BlcaKHat 

> The data i am using is not Free or sharable in my country. I am working under ( Indian institute of Remote sensing ). I am not allowed to take the data. I will try to give you the details of data tommorow.

Got it, right now pycoal only aims to work with [AVIRIS-C](https://aviris.jpl.nasa.gov/data/index.html) and [AVIRIS-NG](https://avirisng.jpl.nasa.gov/data.html) data.

By the way, AVIRIS-NG had flown many campaigns in India, you can see them here https://avirisng.jpl.nasa.gov/alt_locator/

**Comment by BlcaKHat** [comment]
![imggg](https://user-images.githubusercontent.com/16970999/38954487-62cd5a92-436f-11e8-9f98-26d89dd29281.png)

this is the image..

**Comment by BlcaKHat** [comment]
you try to get data if possible

**Comment by lewismc** [comment]
@BlcaKHat please see the following information
```
NOTE: If you encounter difficulty accessing any data, please contact Sarah Lundeen <sarah.r.lundeen@jpl.nasa.gov> and we will make the data available for you.
```

**Comment by BlcaKHat** [comment]
@lewismc  thank you so much.
