### ISSUE TITLE
verify licensing of fall report requisites

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#15]
We need to make sure that all of the files added by Pull Request https://github.com/capstone-coal/coal/pull/14 are compatible with the Apache license, as applicable with respect to Fair Use. Assigning to myself.

Having all the documents in the application source is not that elegant, but our instructors have told us to use a single repository. Please file an issue if it is desired to find another option.

**Comment by lewismc** [comment]
@browtayl is this resolved?

**Comment by ghost** [comment]
@lewismc negative. I'll take care of it this week.

**Comment by ghost** [comment]
According to the pull request, the added files are `IEEEtran.cls`, `pgfgantt.sty`, and `DejaVuSansMono.sty`. As I recall, these were copied directly from my Debian system so the licenses should be free and easy to find. Understanding the legal implications of the licenses is not as straightforward, so I'll find each license first and then analyze them.

Recall that it is possible to license components separately, and that Debian uses a convenient [format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) that we might want to adopt. After I make sure these licenses are compatible, I can file another issue to create a copyright file if desired. It would be better if we didn't have to redistribute these files at all, but they are required to make the report build using the outdated software on OSU Engineering servers.

```
taylor@debian:~$ locate IEEEtran.cls
/usr/share/texlive/texmf-dist/tex/latex/IEEEtran/IEEEtran.cls
taylor@debian:~$ dpkg -S /usr/share/texlive/texmf-dist/tex/latex/IEEEtran/IEEEtran.cls
texlive-publishers: /usr/share/texlive/texmf-dist/tex/latex/IEEEtran/IEEEtran.cls
taylor@debian:~$ less /usr/share/doc/texlive-publishers/copyright 
taylor@debian:~$ cp /usr/share/doc/texlive-publishers/Licenses.gz /tmp/
taylor@debian:~$ gunzip /tmp/Licenses.gz 
taylor@debian:~$ less /tmp/Licenses 
taylor@debian:~$ grep IEEEtran /tmp/Licenses 
IEEEtran: lppl1.3
texmf-dist/bibtex/bib/IEEEtran/*
texmf-dist/bibtex/bst/IEEEtran/*
texmf-dist/doc/latex/IEEEtran/*
texmf-dist/tex/latex/IEEEtran/*
```

So the IEEE file is under the [Latex Project Public License Version 1.3](http://www.ctan.org/license/lppl1.3).

Additional licenses to be found shortly.

**Comment by lewismc** [comment]
Thanks @browtayl if I were you I wouldn't worry about this. We do not need to distribute these files. The fact that they reside in a SCM server somewhere does not mean we are breaking copyright and/or licensing agreements.
We can merely link all 'documentation' from the main coal website... whenever it is updated!

**Comment by ghost** [comment]
@lewismc Point taken, I just created the issue to be certain that I wasn't infringing when I copied in these files. Arguably having it in version control does constitute redistribution, so I'll just really quickly look at the other licenses before closing the issue, and we can add a copyright file or remove them later as necessary.

The pgfgantt file is under the same license:

```
taylor@debian:~$ locate pgfgantt.sty
/usr/share/texlive/texmf-dist/tex/latex/pgfgantt/pgfgantt.sty
taylor@debian:~$ dpkg -S /usr/share/texlive/texmf-dist/tex/latex/pgfgantt/pgfgantt.sty
texlive-pictures: /usr/share/texlive/texmf-dist/tex/latex/pgfgantt/pgfgantt.sty
taylor@debian:~$ less /usr/share/doc/texlive-pictures/copyright 
taylor@debian:~$ cp /usr/share/doc/texlive-pictures/Licenses.gz /tmp/
taylor@debian:~$ gunzip /tmp/Licenses.gz 
gzip: /tmp/Licenses already exists; do you wish to overwrite (y or n)? y
taylor@debian:~$ less /tmp/Licenses 
taylor@debian:~$ grep pgfgantt /tmp/Licenses 
pgfgantt: lppl1.3
texmf-dist/doc/latex/pgfgantt/*
texmf-dist/source/latex/pgfgantt/*
texmf-dist/tex/latex/pgfgantt/*
```

And the same with the font style file:

```
taylor@debian:~$ locate DejaVuSansMono.sty
/usr/share/texlive/texmf-dist/tex/latex/dejavu/DejaVuSansMono.sty
taylor@debian:~$ dpkg -S /usr/share/texlive/texmf-dist/tex/latex/dejavu/DejaVuSansMono.sty
texlive-fonts-extra: /usr/share/texlive/texmf-dist/tex/latex/dejavu/DejaVuSansMono.sty
taylor@debian:~$ less /usr/share/doc/texlive-fonts-extra/copyright 
taylor@debian:~$ cp /usr/share/doc/texlive-fonts-extra/Licenses.gz /tmp/
taylor@debian:~$ gunzip /tmp/Licenses.gz 
gzip: /tmp/Licenses already exists; do you wish to overwrite (y or n)? y
taylor@debian:~$ less /tmp/Licenses 
taylor@debian:~$ grep dejavu /tmp/Licenses 
dejavu: lppl
texmf-dist/doc/fonts/dejavu/*
texmf-dist/fonts/afm/public/dejavu/*
texmf-dist/fonts/enc/dvips/dejavu/*
texmf-dist/fonts/map/dvips/dejavu/*
texmf-dist/fonts/tfm/public/dejavu/*
texmf-dist/fonts/truetype/public/dejavu/*
texmf-dist/fonts/type1/public/dejavu/*
texmf-dist/fonts/vf/public/dejavu/*
texmf-dist/tex/latex/dejavu/*
```

Debian's obsession with upholding its [social contract](https://www.debian.org/social_contract) makes it a really nice environment for free software development.

Here's a little more about the LPPL:
https://en.wikipedia.org/wiki/LaTeX_Project_Public_License

It looks like a permissive copyright license, so it's cool to redistribute the unmodified files.

Assigning to @lewismc for review. Close or reassign as desired, and optionally create and assign to me a new issue to create a Debian copyright file.

**Comment by ghost** [comment]
@lewismc this issue has been marked as "review" for some time. based on the findings above, it looks like we're safe to redistribute all the files in question. if you agree, then this issue can be closed.

**Comment by lewismc** [comment]
ack
