### ISSUE TITLE
Sphinx doesn't support Python 3.3

### ISSUE THREAD

**Issue by EvandroCT** [capstone-coal/pycoal#156]
When I performed [this PR](https://github.com/capstone-coal/pycoal/pull/154#issuecomment-393715423), I wasn't able to pass through [Job 2 of the Travis #377 build](https://travis-ci.org/capstone-coal/pycoal/builds/384559362). Taking a look at the Job log, there was an error at [line 725](https://travis-ci.org/capstone-coal/pycoal/jobs/384559364#L725): "ERROR: Sphinx requires at least Python 2.7 or 3.4 to run."

After a quick survey I could confirm [here](http://www.sphinx-doc.org/en/stable/intro.html#prerequisites) and [here](https://pypi.org/project/Sphinx/1.7.4/) that 1.7.4- version of the Sphinx library in fact doesn't work with Python 3.3, which is the version used in the Job 2 of the Travis build.

In order to track when this issue have began, I took a look the [master branch](https://github.com/capstone-coal/pycoal/commit/9b123717a68ab742881dbab119708cd8ebcd3f71) and [saw the same issue happen](https://travis-ci.org/capstone-coal/pycoal/jobs/378014524#L750). When we go up to the [parent commit](https://github.com/capstone-coal/pycoal/commit/187710ffa20041b34e2c8ffd631814b9a250fb1c) we see there's no Travis build for it. Then, I created the [test-sphinx-issue](https://github.com/capstone-coal/pycoal/tree/test-sphinx-issue) branch in order to test Travis build and it [has succeeded](https://travis-ci.org/capstone-coal/pycoal/builds/391476343). So, we can conclude the issue begin with the commit [9b12371](https://github.com/capstone-coal/pycoal/commit/9b123717a68ab742881dbab119708cd8ebcd3f71), from which I branched. 

With that in mind, I think we have to chose one of the two: to leave Python 3.3 behind or to pick another documentation generator. This sole pending issue is blocking my entire PR merge.

Cheers!

**Comment by lewismc** [comment]
Please just remove build support for Python 3.3 thanks

**Comment by EvandroCT** [comment]
@lewismc Done. Please, check this out https://github.com/capstone-coal/pycoal/pull/155
