### ISSUE TITLE
Create a score map

### ISSUE THREAD

**Issue by EvandroCT** [capstone-coal/pycoal#157]
This issue arose when I needed to store the confidences' values computed by SAM for each pixel when performing a mineral classification. The idea is to find a way to store those values somewhere to be able to be referred further on. I've already (ad hoc) modified mineral API to create a separated ENVI image in which each pixel holds it's score, but we can think of creating an additional (and optional) layer in the classified image in order to hold those values.

**Comment by lewismc** [comment]
This is an excellent suggestion and I may have additional advice on how we can address this. I'll think a bit more and we can discuss in the future.

**Comment by EvandroCT** [comment]
@lewismc [This ENVI Classification Files specification ](http://www.harrisgeospatial.com/docs/ENVIClassificationFiles.html) states that a classified image (like the one produced by the current Pycoal's SAM implementation) must have only one band, corresponding to the band with the classification labels information. Because of this I think we could extend the SAM's classifier callback arguments list to encompass the path of another ENVI image used to hold only the score values, beside the classified image itself. If the user let blank the new argument, the function could behave by ignoring the score map file creation.

**Comment by lewismc** [comment]
@EvandroCT +1 I agree with the suggestion.

**Comment by lewismc** [comment]
@EvandroCT is this implemented?
