### ISSUE TITLE
Update Community Involvement Section of README

### ISSUE THREAD

**Issue by theoilie** [capstone-coal/pycoal#163]
1. The README has a Google Group mailing list icon that redirects to [a page](https://groups.google.com/forum/#!forum/coal-capstone) saying, "This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access." @lewismc Are you the owner of this group?

2. I created a capstone-coal Slack organization that I will make a corresponding PR for shortly so that it can be displayed in the README.

**Comment by theoilie** [comment]
From following the official [development workflow](https://github.com/capstone-coal/pycoal/wiki/COAL-Development-Workflow), I'm unable to create any new branches since I don't have access. Should we be using a different workflow that involves forking the repo first? Otherwise wouldn't anyone who wants to contribute need to already have write permission for new branches? @lewismc

**Comment by lewismc** [comment]
Hi @Lactem Google changed the GGroup permission such that it became private again... I made it public so the above issue should now be resolved. Let me know if this is the case.

**Comment by lewismc** [comment]
Also, please label your issues when you create them. Thank you v much.

**Comment by mjn0898** [comment]
Slack icon pixel width regressed, reinstating previous fix by @Lactem
