### ISSUE TITLE
Failing Nosetest

### ISSUE THREAD

**Issue by theoilie** [capstone-coal/pycoal#164]
When running `nosetests`, the test `environment_test.test_intersect_proximity` fails with the following error:
` 
File "environment.py", line 180, in proximity
    if returncode != 0:
UnboundLocalError: local variable 'returncode' referenced before assignment
`

I think the solution is simply to add `returncode = 0` to the beginning of the function call (below "def proximity(...)" in [environment.py](https://github.com/capstone-coal/pycoal/blob/master/pycoal/environment.py)).

Note: The Travis builds only pass because this test is skipped, which is triggered by the CONTINUOUS_INTEGRATION flag. From the log of the most recent build:
`environment_test.test_intersect_proximity ... SKIP: Skip test because GDAL not installed on server`

**Comment by lewismc** [comment]
I honestly didn't even know this @Lactem we should fix this... well observed.

**Comment by lewismc** [comment]
Please submit a PR when you can, thanks
