### ISSUE TITLE
Incorporate spectral functionality to increase parallelization flexibility for SAM algorithm

### ISSUE THREAD

**Issue by Luner** [capstone-coal/pycoal#169]
The bottleneck in the loop for the SAM algorithm can be found in the function call to the spectral library to calculate spectral angles.

```
#calculate spectral angles
angles = spectral.spectral_angles(
   resampled_pixel[numpy.newaxis, numpy.newaxis, ...],
   library.spectra)
```

It could improve runtimes to move the function call into pycoal so that we could flexibly structure the pixel calculations to run on different parallelization frameworks.

**Comment by lewismc** [comment]
@Luner thanks for registering this. Please use tags in the future to describe the issue.
