### ISSUE TITLE
Use PyTorch to speed up SAM algorithm in mineral.py

### ISSUE THREAD

**Issue by TinyBugBigProblem** [capstone-coal/pycoal#172]
Currently I've set up a module (parallel.py) to implement data parallelism using PyTorch in order to improving runtime.

The idea is to break up this code into more modular functions that a PyTorch Model class will be able to use more effectively.

            '# read the pixel from the file
            pixel = data[x,y]

            # if it is not a no data pixel
            if not numpy.isclose(pixel[0], -0.005) and not pixel[0]==-50:

                # resample the pixel ignoring NaNs from target bands that don't overlap
                # TODO fix spectral library so that bands are in order
                resampled_pixel = numpy.nan_to_num(resample(pixel))

                # calculate spectral angles
                angles = spectral.spectral_angles(resampled_pixel[numpy.newaxis,
                                                                 numpy.newaxis,
                                                                 ...],
                                                  library.spectra)

                # normalize confidence values from [pi,0] to [0,1]
                for z in range(angles.shape[2]):
                    angles[0,0,z] = 1-angles[0,0,z]/math.pi

                # get index of class with largest confidence value
                index_of_max = numpy.argmax(angles)

                # get confidence value of the classied pixel
                score = angles[0,0,index_of_max]

                # classify pixel if confidence above threshold
                if score > threshold:

                    # index from one (after zero for no data)
                    classified[x,y] = index_of_max + 1

                    if scores_file_name is not None:
                        # store score value
                        scored[x,y] = score`

Currently I have run into issues trying to do this but I believe this is because I have not properly broken down the image into smaller portions for the Model to process. I will be working more on setting up a better DataSet class that will allow the model to work on smaller pieces of the image.

**Comment by lewismc** [comment]
Superseded by #196
