### ISSUE TITLE
Readthedocs.io build failing

### ISSUE THREAD

**Issue by mjn0898** [capstone-coal/pycoal#173]
When investigating why the outdated build is not updating, attempts to rebuild both the stable and latest version of the project both failed, returning the error: 'RuntimeError: Python version >= 3.5 required' while running setup.py in both cases.

**Comment by lewismc** [comment]
@mjn0898 where is the build log... please reference it here. There is lacking context. Please fill in the blanks.

**Comment by lewismc** [comment]
@mjn0898 here is the latest build log
https://readthedocs.org/projects/pycoal/builds/9755918/
I added https://github.com/capstone-coal/pycoal/blob/master/.readthedocs.yml
Either edit the build to include the relevant theme or else just remove the theme and use the default RTD theme... personally I think it would be easier if we did the latter. 
This is a trivial item (should take no longer than 30 minutes) so please don't spend too much time on it. Thanks

**Comment by lewismc** [comment]
Fixed in https://github.com/capstone-coal/pycoal/commit/6ea923808db9c5b143968d5e7887eae37deba40f
There are subsequent issues with the markup. I will address those in a separate ticket.
