### ISSUE TITLE
Parallelize SAM algorithm in mineraly.py using Joblib

### ISSUE THREAD

**Issue by aheermann** [capstone-coal/pycoal#177]
Along with dask and Pytorch, we want another option for parallelization. This one is Joblib, a Python library often used for "embarassingly parallel for loops", that just runs on the CPU. The target code to parallelize is the same as issues #168 and #172, and this works to give users more choice when running Pycoal. Documentation on Joblib is linked below. 
https://joblib.readthedocs.io/en/latest/index.html
https://joblib.readthedocs.io/en/latest/parallel.html

**Comment by lewismc** [comment]
Thanks @aheermann is there a PR for this yet?

**Comment by aheermann** [comment]
Not yet, @lewismc. I made a branch for the issue, but I am still making a few fixes
