### ISSUE TITLE
Remove repeated calculation for spectral angles from SAM algorithm

### ISSUE THREAD

**Issue by Luner** [capstone-coal/pycoal#188]
The call to spectral_angles within the SAM algorithm looks like this:

```
def spectral_angles(data, members):
    m = np.array(members, np.float64)
    m /= np.sqrt(np.einsum('ij,ij->i', m, m))[:, np.newaxis]

    norms = np.sqrt(np.einsum('ijk,ijk->ij', data, data))
    dots = np.einsum('ijk,mk->ijm', data, m)
    dots = np.clip(dots / norms[:, :, np.newaxis], -1, 1)
    return np.arccos(dots)
```

This function is called for each pixel yet the input variable "members" will always remain the same.  Thus we can take the transformations done with "members" and preform them once before looping through the data.

**Comment by lewismc** [comment]
+1
