### ISSUE TITLE
Collapse SAM algorithm to operate column by column rather than pixel by pixel

### ISSUE THREAD

**Issue by Luner** [capstone-coal/pycoal#196]
SAM currently loops through every pixel and preforms necessary operations.  It is possible to change this such that operations are preformed on a column by column basis.

This would in theory noticeably boost performance.

**Comment by lewismc** [comment]
+1

**Comment by Luner** [comment]
This branch is built off of ISSUE-192.  It runs very quickly, reducing the runtime from about 45 minutes to 6 minutes. 

I do however experience issues when running the process on my desktop.  It seems likely that it is due to either an issue with the power supply or overheating processor as I build it into a small case with little airflow and a relatively low wattage PSU.

Essentially about 50% of the time my desktop will just shut down without warning and the other 50% of the time the process will complete.  While the runtime is longer, I do not experience the issue on my laptop.

I do not think this will be an issue for anyone else but still something to consider if testing this branch.

**Comment by lewismc** [comment]
Cool, can you point me to the branch please? Thank you

**Comment by Luner** [comment]
The branch is labeled ISSUE-196

**Comment by lewismc** [comment]
Will try it later on thanks

**Comment by lewismc** [comment]
@Luner I tried to run the example mineral classification on the larger scene with no luck. Program stalled early on after RGB image generation. I'm going to attempt a profiling session to see what is going on.

**Comment by lewismc** [comment]
Running some diagnostics
```
import cProfile
...
    # generate a mineral classified image
    cProfile.runctx('mineral_classification.classify_image(input_filename, classified_filename)', None, locals())
```
... let it run for a while, then kill it and see what is going on
```
$ python3 example_mineral.py
Unable to parse bad band list (bbl) in header as integers.
Saving /Users/lmcgibbn/Downloads/pycoal/examples/ang20150420t182050_corr_v1e_img_rgb.img // takes about 0.6 seconds which is great
Unable to parse bad band list (bbl) in header as integers.
^C         167678893 function calls (167678887 primitive calls) in 661.905 seconds // this is 11 minutes runtime

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)

...

        1  467.125  467.125  661.857  661.857 bilfile.py:312(read_subimage)

...
        1    0.000    0.000  661.905  661.905 mineral.py:310(classify_image)
        1    0.000    0.000  661.905  661.905 mineral.py:40(SAM)
...

 83832967  115.847    0.000  115.847    0.000 {method 'fromfile' of 'array.array' objects}
  
...

 83832969   78.885    0.000   78.885    0.000 {method 'seek' of '_io.BufferedReader' objects}
```
A couple of questions/observations.

1. Can anyone else reproduce this behaviour? 
2. From the above it is pretty easy for us to see which calls are taking loads of time. Most of the calls are primitive in nature meaning that we _may_ have a small number of buggy recursive calls which leave us with the  halting problem.

**Comment by lewismc** [comment]
I believe that the hanging issue above was caused by incorrectly specifying values for `MINERAL_SUBSET_ROWS` and `MINERAL_SUBSET_COLS` configuration parameters in `constants.py`.
I've now set these to 
```
MINERAL_SUBSET_ROWS = None
MINERAL_SUBSET_COLS = None
```
...re-running re job

**Comment by lewismc** [comment]
Job finished results as follows
```
2019-11-15 07:53:52,608 Starting mineral classification with input file 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr' and spectral library '../pycoal/tests/s07_AV95_envi.hdr'.
2019-11-15 07:53:52,608 Instantiated Mineral Classifier with following specification: -classifier function 'SAM'
2019-11-15 07:53:52,608 Starting generation of three-band RGB image from input file: 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr' with following RGB values R: '680.0', G: '532.5', B: '472.5'
2019-11-15 07:53:53,142 Saving RGB image as 'ang20150420t182050_corr_v1e_img_rgb.hdr'
2019-11-15 07:53:53,256 Completed RGB image generation. Time elapsed: '0:00:00'
2019-11-15 07:53:53,301 Starting Mineral Classification for image 'avng.jpl.nasa.gov/AVNG_2015_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr', saving classified image to 'ang20150420t182050_corr_v1e_img_class.hdr'
2019-11-15 07:53:53,356 Classifying a 14674X739 image
2019-11-15 08:05:30,470 Completed Mineral Classification. Time elapsed: '0:11:37'
```
We need to validate the results... that's the next step. This is a huge speedup for sure.

**Comment by Luner** [comment]
The results seem to be the same.  There are a few pixels that were classified differently but it seems like this is due to slight changes in calculation results.

Basically when looking for the max angle, sometimes there were a pixel that has a few that angles that were the same value and max would find the first.  These small changes made it so that these values that were previously the same were slightly different (at least less than 10e-8 difference).

**Comment by lewismc** [comment]
OK, please submit a PR for this branch if you are happy with it so I can review the code. This is a huge step forward.
