### ISSUE TITLE
environmental correlation

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#20]
this issue is for implementation of mining/environment correlation, mainly GIS stuff. it would be straightforward to bundle the temporal analysis with this as well, but we can decide on that later. assigning to myself.

**Comment by ghost** [comment]
I have created a work-in-progress [pull request](https://github.com/capstone-coal/coal/pull/24) containing a skeleton and a [more detailed sketch](https://github.com/browtayl/coal/blob/98cf8f9c9291f7c88c8ef62518374a66c2478a70/docs/gis-processing.jpg) of GIS processing.

The big picture is that I've outlined a utility function `combine` which takes user-defined functions for combining raster images and choosing layers, applies them to the GIS and classified data, and saves the result to a file. The user-defined functions could be used to generate mining training data or correlate environmental impacts.

I still need to figure out how to deal with GDAL's data set abstraction which may require temporary files for intermediate data. Also I won't be able to test these functions until I have found suitable data to work with. There are probably some [unknown unknown](https://en.wikipedia.org/wiki/There_are_known_knowns) bugs as well.

**Comment by ghost** [comment]
as we have discussed, this issue has been reinterpreted to mean providing helper functions for GIS processing of [water quality data](https://github.com/capstone-coal/pycoal/issues/26#issuecomment-285649001). this means finding a relevant data set in the national water quality database, georeferencing it, and plotting it in QGIS.

I think it would be best to push this back to the 0.3 milestone. I can still clean out broken files for 0.2.

**Comment by lewismc** [comment]
ack

**Comment by ghost** [comment]
To complement the national hydrography dataset downloaded previously for environmental analysis, I have acquired topographic contours from the National Map for the Shiprock E, New Mexico [region](https://www.sciencebase.gov/catalog/item/581d24cae4b08da350d59238). The contours are in FileGDB format which (c'est la vie) is not supported by the outdated GDAL library linked with QGIS. This is fixed in later versions, so when I build these from source it will be imported correctly. For now, it is [possible](https://gis.stackexchange.com/questions/108006/how-to-convert-data-from-a-gdb-into-a-shapefile-without-arcmap) to use the `ogr2ogr` utility from a recent GDAL to convert FileGDB to Shapefile:
```
$ ogr2ogr -f "ESRI Shapefile" Elev_322228_Shiprock_E_1X1.shp Elev_322228_Shiprock_E_1X1.gdb
```
I've [combined it](https://drive.google.com/open?id=0BxysdOuBmaIGWFZIaW9uNnI2LVU) with the incoming mining classification and environmental data and saved my work in a QGIS project file which can be shared and reused given the requisite geographic files.

At first glance, the 1 meter scans are dominated by schwertmannite classifications and show other differences with the 2.7 meter scan we first looked at. There are concentrations of mine classifications around a number of water features, further suggesting potential water impacts.

I will have to further analyze the water quality data to figure out what specifically to measure for. Ideally I would be able to plot quantities at the sites on the map, allowing us to compare upstream and downstream water quality for some factor.

**Comment by ghost** [comment]
Here's a [more detailed picture](https://drive.google.com/open?id=0BxysdOuBmaIGTXdrTThFWEU4RUk).

**Comment by ghost** [comment]
And a [close-up](https://drive.google.com/open?id=0BxysdOuBmaIGMjlVbGdidU1zekE) of mine classifications along water features.

**Comment by ghost** [comment]
Note that the high-res data is much less dense with mine classifications than our original image and shows fewer anomalies. I'm inclined to believe it's more reliable.

**Comment by lewismc** [comment]
This is really cool.
A quick question here @browtayl with regards to the manual orientation we are currently required to do when loading classified data products into QGIS e.g. 
 * conversion of FileGDB to Shapefile, and 
 * the other orientation issue you addressed with your patch o GDAL
Is is wise to open tickets which add address these issues wherever they are required in the pycoal workflow?

**Comment by ghost** [comment]
Another image [came in](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-294324683) and there are five more to go. I applied the mining classifier and plotted another [overview](https://drive.google.com/open?id=0BxysdOuBmaIGNzJyRnBsNm14TUE) and [detail](https://drive.google.com/open?id=0BxysdOuBmaIGRk1YbXBtTXNfTHM) as before. The additional data show more evidence of acid mine drainage classifications (orange schwertmannite pixels) along waterways as well as artificial structures. A closer analysis of the images might reveal additional relevant classes that were not present in the original image. I'm also thinking of writing a method to generate visible-light representations so we can get a better idea what we're looking at.

I hid the original 2.7m scan which is a lot more noisy. The 1m images do not contain sludge classifications or edge distortions, corroborating the idea that these are sensor artifacts. Some of the mine classifications don't overlap between the 2.7m and 1m images which is unexpected. Assuming that the 1m images are more accurate, we might ask why this is so. These data suggest that high-resolution scans may be preferable for detailed analysis but that low-resolution scans may still be useful for finding evidence of mining.

@lewismc Regarding the workflow, both FileGDB and ENVI rotation should be supported with a QGIS built against GDAL 2.2.0+. My Debian Stable system has rather old versions of these programs. I could build an up-to-date version right now, but it is easier to work around the problem on the command line than to compile all the dependencies. My recommendation is to wait for the GDAL release and then build everything from source. Then we can just note the version requirements in our documentation. Eventually the updated software will make it into the latest GNU/Linux distributions. If need be we could release our build as an executable or system image, but it is arguably the end users' responsibility to update their software.

**Comment by ghost** [comment]
One relatively painless thing I could do is use [checkinstall](https://wiki.debian.org/CheckInstall) to package up the the GDAL and QGIS builds for redistribution. This would make them easy to share. It would introduce a soft dependency on an x86_64 Debian-based system (Debian, Ubuntu, Linux Mint, etc.).

It would be less painless to distribute a virtual machine image containing preinstalled software as well as example GIS files that could be run to demo the San Juan imagery.

**Comment by ghost** [comment]
I downloaded [road data](https://www.sciencebase.gov/catalog/item/581d6769e4b0dee4cc8e5c28) from the National Transportation Dataset which appears to be more accurate than the OpenStreetMap data I downloaded through QGIS. Here's an [overview](https://drive.google.com/open?id=0BxysdOuBmaIGMW5xRFc4VWkzZlE) with this data.

Here are some close-ups of the mine classifications around a [pond](https://drive.google.com/open?id=0BxysdOuBmaIGczd0ZmlDRlZQQ0k) and [water body](https://drive.google.com/open?id=0BxysdOuBmaIGODBtckI4Rlo1Y2M).

**Comment by ghost** [comment]
Here's a [tutorial](http://www.qgistutorials.com/en/docs/making_a_map.html) on using QGIS to generate print-quality maps. This will give us a nicer final product than the screenshots I have been sharing.

**Comment by ghost** [comment]
It's interesting to note that now that we have mine pixels intersecting with streams and water bodies it would be possible to do the overlay thing we talked about months ago. I think that the water quality measurements will end up being more educational, however.

**Comment by ghost** [comment]
as part of this issue i will share my QGIS project file which can be used to replicate my environmental correlation efforts.

**Comment by ghost** [comment]
@lewismc @heidiaclayton @xiaomei7 The [latest](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-296419220) mining-classified imagery has added some dramatic new data points. Check out these overviews [with](https://drive.google.com/open?id=0BxysdOuBmaIGa0doaU1lcjVkdkU) and [without](https://drive.google.com/open?id=0BxysdOuBmaIGZ3NYbjdNVHBBbkE) the low-res scan, and this [detail](https://drive.google.com/open?id=0BxysdOuBmaIGRUtHNTJwMUpldVU). Once the last two images complete we'll definitely want to update the visualizations on the website and poster.

**Comment by ghost** [comment]
it is clear that there are significant concentrations of mine classifications following waterways and roads. it is even possible to distinguish opposing stream banks. note also that there are more red pixels ("sludge") where the coal conveyor and pile is.

it's not obvious why some of the scans seem to be so much more dense. here is where the [threshold](https://github.com/capstone-coal/pycoal/issues/65) parameter might be useful.

**Comment by ghost** [comment]
here's a closer [close-up](https://drive.google.com/open?id=0BxysdOuBmaIGdkFTMVNrdVRBN2M) clearly showing mine classifications along streams and roads. it's remarkable how well these line up with the transport and hydro data.

**Comment by ghost** [comment]
a couple more close-ups of [streams](https://drive.google.com/open?id=0BxysdOuBmaIGY2RDNDFyaXlRREU) and [excavation](https://drive.google.com/open?id=0BxysdOuBmaIGcTMtOGZvQmdTOWs).

**Comment by ghost** [comment]
It looks like the data I downloaded from the [Water Quality Portal](https://www.waterqualitydata.us/portal/) might not be that helpful. I have been analyzing CSV files with LibreOffice Calc. Recall that acid mine drainage is broadly described as the transition of iron sulfide (pyrite) into an array of secondary compounds with acidic chemistry. The water quality data is even more sparse than the points on the map suggest, both geographically and chemically. There is no data on iron or even pH. The data points on sulfate and alkalinity show no apparent difference at the sites upstream and downstream of the San Juan River, but there were only a handful of measurements collected by hand at [sites](https://drive.google.com/open?id=0BxysdOuBmaIGZVp6bk9MQmlGQzA) of significantly different types (well, reservoir, and flowing stream) at different times. I still think it may be worthwhile to develop the software to plot these data points, but I am now considering going back to the overlay approach to find locations where water features and mine classifications overlap now that we have some more substantial data.

**Comment by ghost** [comment]
Now that the final two images are done, we have the most complete picture of mining classifications: [with](https://drive.google.com/open?id=0BxysdOuBmaIGVmVUVmlaX3I4STA) and [without](https://drive.google.com/open?id=0BxysdOuBmaIGb3hqWGJfSWpfaEE) the low-res image, in the [vicinity](https://drive.google.com/open?id=0BxysdOuBmaIGV3lmRUtPa0s3WGc) of the mine, [along](https://drive.google.com/open?id=0BxysdOuBmaIGSTc1cDA4VmpDaHc) the arroyo, and on the bottom [corner](https://drive.google.com/open?id=0BxysdOuBmaIGYlI1N2tJbzNsdkk) of our data.

Clearly I have the data I need to intersect the streams and water bodies with the mining classifications and to do a statistical analysis. All that skeleton code I commented out may turn out to be very useful after all. What remains to be seen is whether I can finish all this by 2017-05-01. I can no longer wait for GDAL 2.2.0 to be released on that date, so it looks like I'll have to compile a preliminary build.

**Comment by ghost** [comment]
I generated RGB images on the server using the following script in `~/browtayl/issue-20/rgb.py`:
```
#!/usr/bin/env python
# Generate RGB versions of high-res imagery
# Usage: ./rgb.py >> rgb.log 2>&1 &

import os
import time
import re
import sys
sys.path.append('/home/ec2-user/browtayl/pycoal')
import pycoal
import pycoal.mineral

# image files
imageFilenames = [
    '/home/ec2-user/AVNG_data_distribution/L2/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t181345_rfl_v1e/ang20150420t181345_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t190759_rfl_v1e/ang20150420t190759_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t185149_rfl_v1e/ang20150420t185149_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t183606_rfl_v1e/ang20150420t183606_corr_v1e_img.hdr',
    '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr'
]

# save rgb images in `~/AVNG_data_distribution/LC` directory with `_rgb` suffix
rgbPattern = '(.*)L2/(.*/)(.*)(.hdr)'
rgbDirectories = [re.sub(rgbPattern,'\\1LC/\\2',filename) for filename in imageFilenames]
rgbFilenames = [re.sub(rgbPattern,'\\1LC/\\2\\3_rgb\\4',filename) for filename in imageFilenames]

# write completion and running time to log file
logFile = '/home/ec2-user/browtayl/issue-20/rgb.log'

# convert each image
for imageFilename,rgbDirectory,rgbFilename in zip(imageFilenames,rgbDirectories,rgbFilenames):

    # log start time
    with open(logFile, 'a') as log:
        log.write(str(int(time.time()))+' CLASSIFY '+imageFilename+'\n')

    # make directory
    try:
        os.mkdir(rgbDirectory)
    except OSError as error:
        pass

    # classify image
    pycoal.mineral.MineralClassification.toRGB(imageFilename, rgbFilename)

    # log end time
    with open(logFile, 'a') as log:
        log.write(str(int(time.time()))+' SAVED '+rgbFilename+'\n')

# log completion
with open(logFile, 'a') as log:
    log.write(str(int(time.time()))+' DONE.\n')
```
It produced the following output in `~/browtayl/issue-20/rgb.log`:
```
1493351731 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img.hdr
1493351743 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img_rgb.hdr
1493351743 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img.hdr
1493351783 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img_rgb.hdr
1493351783 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img.hdr
1493351820 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_rgb.hdr
1493351820 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img.hdr
1493351856 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_rgb.hdr
1493351856 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img.hdr
1493351889 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_rgb.hdr
1493351889 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t181345_rfl_v1e/ang20150420t181345_corr_v1e_img.hdr
1493351923 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t181345_rfl_v1e/ang20150420t181345_corr_v1e_img_rgb.hdr
1493351923 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t190759_rfl_v1e/ang20150420t190759_corr_v1e_img.hdr
1493351958 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t190759_rfl_v1e/ang20150420t190759_corr_v1e_img_rgb.hdr
1493351958 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t185149_rfl_v1e/ang20150420t185149_corr_v1e_img.hdr
1493351994 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t185149_rfl_v1e/ang20150420t185149_corr_v1e_img_rgb.hdr
1493351994 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t183606_rfl_v1e/ang20150420t183606_corr_v1e_img.hdr
1493352028 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t183606_rfl_v1e/ang20150420t183606_corr_v1e_img_rgb.hdr
1493352028 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img.hdr
1493352063 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img_rgb.hdr
1493352063 DONE.
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t181345_rfl_v1e/ang20150420t181345_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t190759_rfl_v1e/ang20150420t190759_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t185149_rfl_v1e/ang20150420t185149_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t183606_rfl_v1e/ang20150420t183606_corr_v1e_img_rgb.img
Saving /home/ec2-user/AVNG_data_distribution/LC/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img_rgb.img
```
Hopefully I can load these into QGIS to get a more complete picture of the mine.

**Comment by ghost** [comment]
I had to make a minor modification to the RGB routine to correctly handle No Data pixels. I deleted the above images and am running the converter again. If it works, then I'll merge the fix into `development`.

**Comment by ghost** [comment]
Testing each pixel for a No Data value increases the RGB running time significantly, even when I load the image from a file. I'm letting it run but it's wasting my time.

**Comment by ghost** [comment]
When testing for no data pixels, each image is converted to RGB in about ~17 minutes rather than ~40 seconds. The benefit of doing this is that we don't have black bars covering up data in the map. The time cost is puzzling, but maybe it can teach us something about how Spectral Python and/or NumPy handle I/O. In the meantime I'll be working on other things.

**Comment by ghost** [comment]
The [incoming RGB data](https://drive.google.com/open?id=0BxysdOuBmaIGQ2U0LWtRS1hlVEE) is actually really interesting and helps with the environmental correlation. You can see some of the limitations of the National Hydrography Dataset in places where visually there appear to be [drainage ditches](https://drive.google.com/open?id=0BxysdOuBmaIGdFhlcDdaOUZ1dXc) corresponding to some of the coal classifications.

**Comment by ghost** [comment]
Here you can see [the full region](https://drive.google.com/open?id=0BxysdOuBmaIGZ05BY0RONVhmeWc) in RGB and with mining classifications. The [dense region](https://drive.google.com/open?id=0BxysdOuBmaIGaHF2T0JSMnlMYkk) in the center definitely corresponds to the excavation and processing facility. A closer look at the [arroyo](https://drive.google.com/open?id=0BxysdOuBmaIGbW1JdFdEZkNNdXM) shows how the acid mine drainage mineral classification follows the stream bed. For a sense of scale, [notice](https://drive.google.com/open?id=0BxysdOuBmaIGNFNCSmRJbmNWc0E) how the 1 meter pixels compare in size with the stripes in the middle of the road. Check out the visible light image of the [tailing ponds](https://drive.google.com/open?id=0BxysdOuBmaIGU1BYVkJ5VGkwWEU): The bright orange evaporate is not mining classification pixels, it is the true color! A closer look at a [stream](https://drive.google.com/open?id=0BxysdOuBmaIGdE5aaFU1MTY3RDA) above the mine shows that what we are calling schwertmannite appears as visually as blackish chunks on the landscape. You can also see what it looks like on some of the [rills](https://drive.google.com/open?id=0BxysdOuBmaIGcUJUVHZZU1hTMHc) on the hillsides.

This visible-light analysis has only increased my confidence in the quality of the data. Unlike [that West Virginia image](https://github.com/capstone-coal/pycoal/pull/67#issue-222380252) where the classifications were all wrong, all of the orange and red dots seem to be in the right places here.

As noted above, it also informs us of some of the limitations of our vector datasets. Even so it looks like there is a clear link between the distribution of mine waste classifications and streams and water bodies. What I am going to attempt to do to finish environmental correlation is to rasterize the water data, generate a proximity map, use it to filter mine pixels, and possibly compute statistics on the average distance.

**Comment by ghost** [comment]
GDAL has some nice command-line tools so I might be able to save time by calling out to the shell as an unfortunate kluge.

**Comment by ghost** [comment]
I uploaded my build of GDAL to a new software directory on Google Drive. It is a [Debian package](https://drive.google.com/open?id=0BxysdOuBmaIGWHdRWDhsY291MVE) for the amd64 architecture. It may be necessary to install additional dependencies, in which case let me know. Presumably this build won't work on our Amazon Linux server, though it might be possible to convert it to an RPM with [Alien](https://wiki.debian.org/Alien). I assume it would work out of the box on Ubuntu or other Debian-based systems.

**Comment by ghost** [comment]
I successfully built QGIS against the updated GDAL so all of that rotation business is no longer needed. Unfortunately I was unable to use either `checkinstall` or `dpkg-buildpackage` so a plain old `make install` was necessary.

I also successfully used `gdal_rasterize` to rasterize the National Hydrography Dataset onto an AVIRIS scene. Next to generate the proximity and intersection.

**Comment by ghost** [comment]
Interestingly, the nonrotated RGB images generated by PyCOAL look better than the workaround warped ones. This is an unexpected benefit of using a proper build of QGIS.

**Comment by ghost** [comment]
@lewismc I have succeeded in converting vector to raster, generating a proximity map, and intersecting mine classifications. I was able to implement the module as a wrapper around `gdal_rasterize`, `gdal_proximity.py`, and Spectral Python which is called like so:
```
>>> environmentalCorrelation = pycoal.environment.EnvironmentalCorrelation()
>>> environmentalCorrelation.intersectProximity('ang20150420t182050_corr_v1e_img_class_mining.hdr', '/media/study/OSU/spring17/cs463/data/NHDNM/Shape/NHDFlowline.shp', 10.0, 'ang20150420t182050_corr_v1e_img_class_mining_NHDFlowline_correlation.hdr')
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img_class_mining_NHDFlowline.img
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20150420t182050_rfl_v1e/ang20150420t182050_corr_v1e_img_class_mining_NHDFlowline_correlation.img
```
This selects all mine classification pixels that are within 10 meters of a flowline in the National Hydrography Dataset. You can see both the proximity map and the intersection for one of our flightlines in this [screenshot](https://drive.google.com/open?id=0BxysdOuBmaIGOVM4dFo0WFpSTEE). It only takes a minute or two to run the correlation on our data.

Now that this is done I can concentrate on packaging up and documenting the changes. Shout out to @heidiaclayton for feedback and patience. I didn't end up doing the statistical analysis, but this takes us most of the rest of the way to meeting our requirements before the code freeze.

**Comment by ghost** [comment]
It [looks like](https://drive.google.com/open?id=0BxysdOuBmaIGXzFoZldrNzB5Tms) the units are a bit off. I wanted 10 meters and got 40. Guess I'll have to look into that. Still, the basic functionality is there.

**Comment by ghost** [comment]
Fixed the issue with the units so the distance [comes out right](https://drive.google.com/open?id=0BxysdOuBmaIGSUxkQ0h1aUNkZFk).

**Comment by ghost** [comment]
I ran the environmental correlation over all the high resolution San Juan images against the National Hydrography Dataset flowlines which you can see in this [overview](https://drive.google.com/open?id=0BxysdOuBmaIGMWo5dEhNZEpGX00). This identifies all mine pixels within ten meters of a stream and preserves the classification types. It doesn't necessarily tell us anything we didn't already know, but it allows us to drill down to the level of detail we're looking for. The same could be done with the water body layers or really any vector layer, but the streams are sufficient for demonstration.

**Comment by ghost** [comment]
I implemented a unit test using vector and raster [subimages](https://drive.google.com/open?id=0BxysdOuBmaIGd1l6aEl2dHB4VU0) created with QGIS and GDAL. The process for creating these subimages is described in the test file.

**Comment by ghost** [comment]
The [unit test](https://github.com/capstone-coal/pycoal/pull/85) is [skipped](https://docs.python.org/2.7/library/unittest.html#unittest.skipIf) on the test server because the proper version of GDAL is not installed. It might be possible to pull in the .deb file I generated above, but for now the test can be run locally with `nosetests` as long as the `CONTINUOUS_INTEGRATION` [environment variable](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) is not set.

**Comment by ghost** [comment]
@lewismc The environmental correlation module now implements the basic functionality for overlaying mine classifications and water data to within some distance in meters. Note that the intermediate feature and proximity rasters are also written to the output directory.

GDAL is invoked through a subprocess call rather than the Python interface, so it is necessary to have the proper version installed to avoid rotation problems. Obviously this is a kluge, but it was the best way to avoid mucking around with GDAL's ugly Python bindings given the time constraints.

I have merged this into `development` so I am closing this issue. There is plenty of room for enhancement which can be addressed in future issues.

**Comment by ghost** [comment]
As part of this issue I also built GDAL and QGIS from source which will be documented on the website.
