### ISSUE TITLE
SAM_joblib update

### ISSUE THREAD

**Issue by aheermann** [capstone-coal/pycoal#202]
Updating the code in SAM_joblib to match that of the other SAM algorithms in ISSUE-193

**Comment by lewismc** [comment]
@aheermann are you going to work on this?

**Comment by aheermann** [comment]
Yes @lewismc , just dev testing to make sure I didn't introduce any new bugs. Hope to have a PR by tomorrow afternoon

**Comment by lewismc** [comment]
Excellent Andrew. Thanks for the update.
-- 

*Lewis*
Dr. Lewis J. McGibbney Ph.D, B.Sc
*Skype*: lewis.john.mcgibbney

**Comment by lewismc** [comment]
Addressed in #203
