### ISSUE TITLE
Clean up SAM

### ISSUE THREAD

**Issue by Luner** [capstone-coal/pycoal#212]
The three SAM functions (SAM_pytorch, SAM_serial, and SAM_joblib) share a lot of the same code with the only difference being the ways in which they populate the classified and scored arrays.

It might make one SAM algorithm that holds this shared code, and will use the method chosen in config.ini to populate the arrays.  It should help with readability.

**Comment by lewismc** [comment]
I see you've created a branch for this @Luner it makes PERFECT sense! I was also getting concerned with the duplication in mineral.py
It's upt to you how you want to merge these contributions into master... if you want to close out without merging #198 in favor of #212 then please do.
