### ISSUE TITLE
Google Group Permissions

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#22]
One of the TODOs in the COAL website [issue](https://github.com/capstone-coal/capstone-coal.github.io/issues/1) is to provide a link to our [Google Group](https://groups.google.com/forum/#!forum/coal-capstone). However, it appears to be "Shared Privately" and I get a permission denied error if I am not logged in.

Assigning to @lewismc to verify that the Google Group permissions are correct and update them if necessary.

**Comment by lewismc** [comment]
This has now been addressed. If there are further issues then let me knowm Thnaks.
