### ISSUE TITLE
pypi package name

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#25]
as previously mentioned, the name "coal" has already been [taken](https://pypi.python.org/pypi/coal/) in the python package index. the project does not seem to be active. it might be worth contacting the package index owner, Martin.Atkins, to see if he would be willing to let us have it. i believe i have found his website here: http://martin.atkins.me.uk/ . we might want to wait until our own project is a little more mature. assigning to @lewismc to decide whether to pursue this.

**Comment by lewismc** [comment]
OK great thank you. I will keep an eye on this and see what is up later on.

**Comment by lewismc** [comment]
I have no heard anything back from the guy above so I'll just rename everything to pycoal. That is the workaround which we can live with.
