### ISSUE TITLE
choose environment case study

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#26]
this issue is to choose a dataset for use as a case study for [environmental correlation](https://github.com/capstone-coal/coal/issues/20).

we are interested in **GIS data** that represents a relatively **simple quantity** to correlate with classified mines. something that can derived from a **single layer** for each pixel would be ideal, such as a distribution of chemical concentrations. it would be possible, if slightly more complicated, to combine this with waterway data. any [vector](http://gdal.org/ogr_formats.html) or [raster](http://gdal.org/formats_list.html) **format supported by GDAL** would be adequate.

if we want to analyze our AVIRIS flightline, we will need a dataset that includes that geographic region. there appear to be plenty of water features around that mine.

furthermore, to facilitate temporal analysis we would want a dataset that is **available for multiple points in time** corresponding to different AVIRIS flights over the same region.

as developers we are mainly concerned with a simple analysis such as "pixels in which mines and significant pollutant concentrations overlap". users of our library would be responsible for implementing more sophisticated analyses.

some examples include tailing ponds, erosion, mine waste, acid drainage, waste rock, and air quality. it was suggested to concentrate on water resources, and it was noted that it would be worth consulting with topic experts at JPL.

assigning to @lewismc as requested in today's meeting.

**Comment by ghost** [comment]
here are a few potential sources from EPA and USGS:
* https://www.epa.gov/geospatial
* https://water.usgs.gov/maps.html
* https://water.usgs.gov/owq/data.html

**Comment by ghost** [comment]
note also that this data should have **comparable resolution** to the AVIRIS imagery.

**Comment by ghost** [comment]
my [skeleton code](https://github.com/capstone-coal/coal/pull/24/files) currently assumes that the input is in vector format, but this is not strictly necessary.

**Comment by ghost** [comment]
@lewismc [the photos of acid mine drainage](https://groups.google.com/d/msg/coal-capstone/R4KGwqVw3Gw/TvzAEf0xAQAJ) got me thinking we might want to quantify something like "abnormal pH" for our case study

**Comment by ghost** [comment]
more from wikipedia:
https://en.wikipedia.org/wiki/Acid_mine_drainage

**Comment by lewismc** [comment]
Yes OK, I am good with that.
Also, as we saw in earlier articles, generally the release of natural contaminants into any waterways is generally considered as environmentally damaging. Here's a more recent example
http://www.snopes.com/2017/02/06/dump-coal-waste-into-streams/
+1 to use abnormal pH which can be detected from tailing ponds, etc.

**Comment by ghost** [comment]
as @lewismc [mentioned](https://groups.google.com/forum/#!topic/coal-capstone/Wy9DTlxUPs8) on the mailing list, a promising potential application of PyCOAL is for [remote sensing of water quality](https://nspires.nasaprs.com/external/solicitations/summary.do?method=init&solId={0E7A02B8-57FB-A842-9EDF-480BE571D420}&path=init) to detect harmful algal blooms (HABs).

we might want to see if pH could be used to quantify these, or whether we might rather study something like "abnormal nitrate concentrations".

**Comment by ghost** [comment]
recall that the [literature on mining identification](https://drive.google.com/drive/folders/0B1hXUEnU66LkRHVzSDYtejl3Nzg) in google drive has a lot of info on acid mine drainage. the big picture is that sulfides released from mining operations react to form acid waste.

**Comment by ghost** [comment]
this [wikipedia page](https://en.wikipedia.org/wiki/Algal_bloom) mentions nutrient pollution of phosphorus, nitrogen, and carbon as possible factors in algal blooms.

**Comment by lewismc** [comment]
@browtayl dynamite... thank you for checking up.

**Comment by ghost** [comment]
cross reference to mailing list thread on [water quality data](https://groups.google.com/forum/#!topic/coal-capstone/MBVIBZBc_cs)

**Comment by ghost** [comment]
@lewismc does that water quality data satisfy the requirements of this issue, or are we looking for more environmental data sets?

**Comment by lewismc** [comment]
No, water quality data is ideal as we discussed at last weeks meeting. Thank you.
