### ISSUE TITLE
API-level documentation

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#30]
Hi @xiaomei7 I would like you to begin working on documentation for the toolkit. This will act as developer level documentation and will be the primary resource for anyone wishing to use Pycoal programmatically so it is a very important task. 

The code is situated at https://github.com/capstone-coal/pycoal/tree/master/docs/source, you should begin with the [introduction.rst](https://github.com/capstone-coal/pycoal/blob/master/docs/source/introduction.rst). The specification for the markup required can be found at http://www.sphinx-doc.org/en/stable/rest.html.

Please create pull requests for the code you write and I will review them for you. Thank you.

**Comment by ghost** [comment]
@lewismc recommend reassigning to @heidiaclayton if no updates from @xiaomei7

**Comment by heidiaclayton** [comment]
[Here](https://pythonhosted.org/an_example_pypi_project/sphinx.html)'s a good resource.

**Comment by xiaomei7** [comment]
@browtayl It's OK I'm currently working on this, I was trying to get familiar with API documentation, wish I can post something valid during the weekend.

**Comment by ghost** [comment]
@xiaomei7 awesome, thanks for letting us know. as mentioned during our meeting, you will need to edit the .rst files to use the correct names of the classes. these can be found in our source files. you may need to push your changes to a feature branch (not master) in the pycoal repo (rather than your personal repo) in order to get the pages to build.

**Comment by ghost** [comment]
@xiaomei7 there's info [here](https://github.com/capstone-coal/pycoal#documentation) on building the docs manually so you don't have to push them to the server to view your changes.

**Comment by xiaomei7** [comment]
Hi, I have tried to build the docs manually on my local computer, and I haven't got any results from the page mineral/mining identification as well as the environment correlation page. Is that normal? @[Here](https://github.com/xiaomei7/ISSUE-30/tree/master/docs/source) is my repository.

**Comment by ghost** [comment]
I would have expected some output since you updated the class names, so
I don't know what could be going wrong. Perhaps Heidi has some insights
since she's done more with Sphinx.


Taylor

**Comment by heidiaclayton** [comment]
@xiaomei7 The path to our code is not set so Sphinx does not know where to find it. You need to edit conf.py in the docs/source folder.

First, there's a section of code that is commented out that looks like this
```
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
```

Change it to this
```
import os
import sys
sys.path.insert(0, os.path.abspath('../../pycoal'))
```

We also have not imported the right things to make autoclass work, so change this line
`extensions = []`

to this
`extensions = ['sphinx.ext.todo', 'sphinx.ext.viewcode', 'sphinx.ext.autodoc']`

**Comment by xiaomei7** [comment]
@lewismc Here is a pull request: #45 .

**Comment by lewismc** [comment]
ack, please merge into master. Good work folks.
