### ISSUE TITLE
clean up docs directory

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#31]
the docs directory is currently a bit of a mess. this enhancement will organize the documents and files in subfolders. assigning to myself.

**Comment by heidiaclayton** [comment]
Heads up, restructext.png and blob.jpg aren't used anymore.

**Comment by lewismc** [comment]
@xiaomei7 this issue is trivial to complete and relates to documentation. Can you please look into completing it? Thank you.

**Comment by ghost** [comment]
@xiaomei7 @lewismc i am reopening this issue because at least one file was moved to the wrong location and because zero attempt was made to ensure that these documents build correctly. they are required by class to build on OSU engineering servers. none of the references to images in the documents were updated, a fact which would have been obvious by running `make all`. i am assigning to myself so that it gets done correctly and will submit a pull request when complete.

**Comment by ghost** [comment]
pull https://github.com/capstone-coal/pycoal/pull/42 merged and closed.
