### ISSUE TITLE
Ensure Linting is part of CI build process

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#35]
There are plenty of good linting programs which ensure that Python code is syntactically accurate. We should build one into the TravisCI configuration.

**Comment by ghost** [comment]
@lewismc @heidiaclayton do either of you recommend a particular linter? i don't have any experience with these in python.

**Comment by kwhitehall** [comment]
Hey @browtayl, [PyLint](https://www.pylint.org/) is a pretty decent one.

**Comment by ghost** [comment]
pull https://github.com/capstone-coal/pycoal/pull/43 merged and closed.
