### ISSUE TITLE
improve mineral classification performance

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#51]
this task is to investigate and improve the performance of the [mineral classifier](https://github.com/capstone-coal/pycoal/blob/master/pycoal/mineral.py).

the loop in the `classifyImage` method is the main concern:
```
        # for each pixel in the image
        for x in xrange(M):

            for y in xrange(N):

                # read the pixel from the file
                pixel = data[x,y]

                # if it is not a no data pixel
                if not numpy.isclose(pixel[0], -0.005) and not pixel[0]==-50:

                    # resample the pixel ignoring NaNs from target bands that don't overlap
                    # TODO fix spectral library so that bands are in order
                    resampledPixel = numpy.nan_to_num(resample(pixel))

                    # calculate spectral angles
                    angles = spectral.spectral_angles(resampledPixel[numpy.newaxis,
                                                                     numpy.newaxis,
                                                                     ...],
                                                      self.library.spectra)

                    # get classification
                    classified[x,y] = numpy.argmin(angles) + 1
```
i have [discussed](https://github.com/capstone-coal/pycoal/pull/44#issuecomment-285932470) likely ways to improve performance:
* fix the spectral library at load or before
* process regionwise rather than pixelwise
* resample down to a smaller number of bands

this depends to some extent on our issues for [logging](https://github.com/capstone-coal/pycoal/issues/46) and [profiling](https://github.com/capstone-coal/pycoal/issues/47), not to mention continued development, so i'm setting to blocked.

**Comment by lewismc** [comment]
Ah ha... ok doke please ignore my comment over on #49 thanks.

**Comment by ghost** [comment]
Since performance  [is becoming a problem](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-292824292), I have added this to the 0.3 milestone. The [logging](https://github.com/capstone-coal/pycoal/issues/46) and [profiling](https://github.com/capstone-coal/pycoal/issues/47) issues are on the 0.2 milestone, but we might want to bump those up as well. Either way, I will make an effort to chip in on those and request assistance from @heidiaclayton .

**Comment by ghost** [comment]
* Another subtlety that may affect performance is the order in which pixels are read. My algorithm reads pixels by the column, but it may be that reading by the row would take better advantage of caching.
* Being able to load the whole image into memory would remove file I/O as a factor, but this is not practical on our AWS system for images [which exceed 25GB](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-292827247).

**Comment by ghost** [comment]
Here are the relevant specifications of the machine:
```
[ec2-user@ip-172-31-28-45 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2400.054
BogoMIPS:              4800.10
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-3
[ec2-user@ip-172-31-28-45 ~]$ cat /proc/meminfo | grep -i memtotal
MemTotal:       16436128 kB
[ec2-user@ip-172-31-28-45 ~]$ uname -a
Linux ip-172-31-28-45 4.4.41-36.55.amzn1.x86_64 #1 SMP Wed Jan 18 01:03:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ghost** [comment]
Here are the processing times and dimensions of the images we have seen so far:

[San Juan Mine, Low Resolution](https://github.com/capstone-coal/pycoal/pull/44#issuecomment-286000261) (AVIRIS-NG):
* 11.5 hours 
* 88 pixels per second
* 151,257 bytes per second
```
>>> spectral.open_image('/home/ec2-user/AVNG_data_distribution/L2/ang20150422t163638_rfl_v1e/ang20150422t163638_corr_v1e_img.hdr')
	Data Source:   '/home/ec2-user/AVNG_data_distribution/L2/ang20150422t163638_rfl_v1e/ang20150422t163638_corr_v1e_img'
	# Rows:           4031
	# Samples:         899
	# Bands:           432
	Interleave:        BIL
	Quantization:  32 bits
	Data format:   float32
>>> (4031*899) / (11.5*60*60)
87.53306763285025
>>> (4031*899*432*(32/8)) / (11.5*60*60)
151257.14086956522
```

[Palisade, Colorado](https://github.com/capstone-coal/pycoal/pull/44#issuecomment-286632396) (AVIRIS-C):
* 6 hours
* 261 pixels per second
* 117,310 bytes per second
```
>>> spectral.open_image('/home/ec2-user/browtayl/pull-request-44/f110609t01p00r11rdn_c/f110609t01p00r11rdn_c_sc01_ort_img.hdr')
	Data Source:   '/home/ec2-user/browtayl/pull-request-44/f110609t01p00r11rdn_c/f110609t01p00r11rdn_c_sc01_ort_img'
	# Rows:           4745
	# Samples:        1192
	# Bands:           224
	Interleave:        BIP
	Quantization:  16 bits
	Data format:     int16
>>> (4745*1192) / (6*60*60)
261
>>> (4745*1192*224*(16/8)) / (6*60*60)
117310
```

[West Virginia](https://github.com/capstone-coal/pycoal/pull/44#issuecomment-286936485) (AVIRIS-C):
* 16 hours
* 61 pixels per second
* 27,587 bytes per second
```
>>> spectral.open_image('/home/ec2-user/browtayl/pull-request-44/f080702t01p00r08/f080702t01p00r08rdn_c_sc01_ort_img.hdr')
	Data Source:   '/home/ec2-user/browtayl/pull-request-44/f080702t01p00r08/f080702t01p00r08rdn_c_sc01_ort_img'
	# Rows:           4723
	# Samples:         751
	# Bands:           224
	Interleave:        BIP
	Quantization:  16 bits
	Data format:     int16
>>> (4723*751) / (16*60*60)
61
>>> (4723*751*224*(16/8)) / (16*60*60)
27587
```

[Craig, Colorado](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-292640083) (AVIRIS-NG):
* 7.2 hours
* 143 pixels per second
* 247,299 bytes per second
```
>>> spectral.open_image('/home/ec2-user/AVNG_data_distribution/L2/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img.hdr')
	Data Source:   '/home/ec2-user/AVNG_data_distribution/L2/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img'
	# Rows:           4254
	# Samples:         872
	# Bands:           432
	Interleave:        BIL
	Quantization:  32 bits
	Data format:   float32
>>> (4254*872) / (7.2*60*60)
143.11296296296297
>>> (4254*872*432*(32/8)) / (7.2*60*60)
247299.2
```

[San Juan Mine, High Resolution #1](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-293130163) (AVIRIS-NG):
* 70 hours
* 57 pixels per second
* 98,870 bytes per second
```
>>> spectral.open_image('/home/ec2-user/AVNG_data_distribution/L2/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img.hdr')
	Data Source:   '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img'
	# Rows:          15862
	# Samples:         909
	# Bands:           432
	Interleave:        BIL
	Quantization:  32 bits
	Data format:   float32
>>> (15862*909) / (70*60*60)
57
>>> (15862*909*432*(32/8)) / (70*60*60)
98870
```
I suspect much of this variability can be explained by the proportion of no-data pixels which don't get fed to the spectral angle mapper. Visually, the West Virginia and high-resolution San Juan Mine images have the lowest proportion of no data pixels. This intuition would be fairly easy to verify more exactly.

I was surprised that there isn't much of a difference with the AVIRIS-C images which have half as many bands as AVIRIS-NG, but this makes sense since both are resampled down to 224 bands before classification.

**Comment by lewismc** [comment]
Thank you for this, extremely helpful and will go very well in our paper.

**Comment by ghost** [comment]
The last two images each took 43 hours to classify at 20GB apiece:
```
[ec2-user@ip-172-31-28-45 ~]$ tail -n5 browtayl/issue-49/classify.log 
1491830486 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img.hdr
1491988498 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_class.hdr
1491988498 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img.hdr
1492144680 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_class.hdr
1492144680 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img.hdr
[ec2-user@ip-172-31-28-45 ~]$ echo $(( (1491988498 - 1491830486) / (60*60) ))
43
[ec2-user@ip-172-31-28-45 ~]$ echo $(( (1492144680 - 1491988498) / (60*60) ))
43
[ec2-user@ip-172-31-28-45 ~]$ python
>>> import spectral
>>> spectral.open_image('/home/ec2-user/AVNG_data_distribution/L2/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img.hdr')
	Data Source:   '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img'
	# Rows:          14549
	# Samples:         797
	# Bands:           432
	Interleave:        BIL
	Quantization:  32 bits
	Data format:   float32
>>> spectral.open_image('/home/ec2-user/AVNG_data_distribution/L2/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img.hdr')
	Data Source:   '/home/ec2-user/AVNG_data_distribution/L2/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img'
	# Rows:          14473
	# Samples:         807
	# Bands:           432
	Interleave:        BIL
	Quantization:  32 bits
	Data format:   float32
>>> sj2 = (14549*797*432*(32/8))
>>> sj3 = (14473*807*432*(32/8))
>>> sj2 / 10.0**9
20.037115584
>>> sj3 / 10.0**9
20.182540608
```

**Comment by lewismc** [comment]
So now all of the current AVIRIS flight lines have been classified?

**Comment by ghost** [comment]
@lewismc negative, there are several more to go. i meant "last" as in "most recent".

**Comment by lewismc** [comment]
ack

**Comment by ghost** [comment]
The latest image took 42 hours:
```
[ec2-user@ip-172-31-28-45 ~]$ tail -n3 browtayl/issue-49/classify.log 
1492144680 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img.hdr
1492298835 SAVED /home/ec2-user/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_class.hdr
1492298835 CLASSIFY /home/ec2-user/AVNG_data_distribution/L2/ang20150420t181345_rfl_v1e/ang20150420t181345_corr_v1e_img.hdr
[ec2-user@ip-172-31-28-45 ~]$ ls -l /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img
-rwxr-xr-x 1 ec2-user ec2-user 19680522048 Mar 28 06:35 /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img
[ec2-user@ip-172-31-28-45 ~]$ ls -l --block-size=G /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img
-rwxr-xr-x 1 ec2-user ec2-user 19G Mar 28 06:35 /home/ec2-user/AVNG_data_distribution/L2/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img
[ec2-user@ip-172-31-28-45 ~]$ echo $(( (1492298835 - 1492144680) / (60*60) ))
42
```

**Comment by ghost** [comment]
A significant change to our algorithm might be able to reduce processing time from L2 to mining-classified image by two orders of magnitude, e.g., from 43 hours to 26 minutes. However, this would require additional development and lose useful intermediate data products.

Currently mineral classification calculates spectral angles for every one of the ~1000 classes in the spectral library and selects the class with the highest confidence value. The result is an image containing the most likely class for every pixel which can be searched for mining or other classes. Note that "most likely" does not necessarily mean "very likely". Benefits of this approach include the ability to identify a wide range of classes as well as facilitate research in other fields. Drawbacks include the processing time and some uncertainty about the validity of the classification.

An alternative would be to use a ~10 class subset of the spectral library and select the class with the highest confidence value above some threshold. The result would be an image containing pixels associated with mining with a certain amount of confidence. Benefits of this approach include rapid processing time, a single step workflow, and a more exact interpretation of the classification. Drawbacks include additional development time, required knowledge of exactly what classes to look for, and lack of intermediate data products.

The current implementation meets our immediate needs, but depending on the long-term application of COAL the alternative might add value and save time.

**Comment by ghost** [comment]
I'm going to push this back to the [0.4](https://github.com/capstone-coal/pycoal/milestone/5) milestone because it's sort of open ended, because initial processing [won't be done](https://github.com/capstone-coal/pycoal/issues/49) for another week, and because we don't yet have an XSEDE allocation.

My first choice would be to simply add an option to load the whole file in memory. Barring significant algorithm changes, I suspect this will provide the biggest improvement for the smallest effort.

**Comment by ghost** [comment]
I believe that the algorithm change I mentioned [above](https://github.com/capstone-coal/pycoal/issues/51#issuecomment-294330086) could be accomplished fairly elegantly, giving us the best of both worlds given sufficient development time. In summary, the mineral classifier constructor could be augmented with optional parameters `classList=None` and `threshold=None`.
* The class list would specify a subset of the spectral library, e.g., `[u'Schwertmannite BZ93-1 s06av95a=b', u'Renyolds_TnlSldgWet SM93-15w s06av95a=a', u'Renyolds_Tnl_Sludge SM93-15 s06av95a=a']`. The full spectral library would be used by default.
* The threshold would choose the most likely class only it is above some confidence value, e.g., `0.75`. In this case it might be desirable to use the [modified spectral angle mapper](http://www.spectralpython.net/class_func_ref.html#msam) algorithm which calculates scores out of 1.0.

Then the classification could be implemented per the following pseudocode:
```
if threshold is None or maxAngle >= threshhold:
    class = index(maxAngle)
```
Given both `classList` and `threshold` parameters, the algorithm would calculate spectral angles for a much smaller subset of the image potentially saving loads of time. Given only the `threshold` parameter, the results would be filtered by confidence value. The `classList` parameter probably doesn't make much sense on its own. The full classification would still be available for exploratory research.

**Comment by ghost** [comment]
The last three images to be classified took a similar amount of time to the previous high-res images:
```
[ec2-user@ip-172-31-28-45 issue-49]$ echo $(( (1492455372 - 1492298835) / (60*60) ))
43
[ec2-user@ip-172-31-28-45 issue-49]$ echo $(( (1492613048 - 1492455372) / (60*60) ))
43
[ec2-user@ip-172-31-28-45 issue-49]$ echo $(( (1492774106 - 1492613048 ) / (60*60) ))
44
```

**Comment by ghost** [comment]
i [found](https://github.com/capstone-coal/pycoal/issues/65#issuecomment-296545183) that subsetting and thresholding does not produce the same results as mineral classification followed by mining classification, though it does save time and add value. computing results for a large spectral library improves the quality of our data, so we may wish to look elsewhere for places to improve. my next best guess would be to resample down to a smaller number of bands and see how that affects the quality. there might also be savings in regionwide processing. of course having 128GB of memory wouldn't hurt.

**Comment by ghost** [comment]
the final two images took 44 and 45 hours respectively.

**Comment by ghost** [comment]
i think what i'll do is add an optional parameter `inMemory=False` to the `MineralClassification` constructor and support loading the full image into memory. we'll need this for testing if we get an XSEDE allocation and it is quite likely where much of the savings lie. then regionwise processing would be irrelevant from a caching perspective. resampling to a smaller dimension would save time, but at the cost of accuracy.

**Comment by ghost** [comment]
the performance of loading entire images is documented here:
http://www.spectralpython.net/fileio.html#loading-entire-images

**Comment by ghost** [comment]
implemented in pull https://github.com/capstone-coal/pycoal/pull/78 and merged into [`development`](https://github.com/capstone-coal/pycoal/pull/73). this isn't going to make processing any faster on our servers, but hopefully it will enable higher performance on more powerful systems.
