### ISSUE TITLE
attribute JPL imagery

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#56]
this issue is to attribute JPL imagery such as our escondida avatar per the [JPL image policy](https://www.jpl.nasa.gov/imagepolicy/). this affects the website, slides, and poster. not sure how to attribute the AVIRIS imagery.

**Comment by ghost** [comment]
* the second draft of the poster now properly attributes the escondida mine image.
* the slides do cite the imagery but do not use the "Courtesy NASA/JPL-Caltech" credit line.
* the website could potentially put the credit line in the alt text so it doesn't clutter the carousel.

**Comment by ghost** [comment]
@lewismc do we need to cite the AVIRIS data itself, and if so how? in general we are only sharing derived products.

**Comment by lewismc** [comment]
No it's OK.

**Comment by ghost** [comment]
@lewismc  i [addressed](https://github.com/capstone-coal/capstone-coal.github.io/pull/24#issuecomment-295056594) the attribution in the website. because the slides link to the source and because they haven't been published anywhere, i suggest we just close this issue and address attribution [when necessary](https://github.com/capstone-coal/capstone-coal.github.io/issues/11).

**Comment by lewismc** [comment]
ACK
