### ISSUE TITLE
backup github

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#62]
this issue is to backup our github repositories, issues, and wikis.

much of our research and development has taken place on github which is a proprietary hosting service. outages, although rare, have affected our team in the past. we cannot necessarily depend on github to preserve our work into the future. a backup of our work would be helpful for archival and scientific purposes once the senior capstone project is complete.

some possibilities include bootstrapping something with `wget`, using [`github-backup`](https://hackage.haskell.org/package/github-backup), [`backup-github.sh`](https://gist.github.com/rodw/3073987), or other tools.

note that records of our work are also distributed across the mailing list, google drive, and personal files.

**Comment by lewismc** [comment]
ack
Amazon Glacier?

**Comment by ghost** [comment]
Setting to unassigned.
