### ISSUE TITLE
DON'T PANIC

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#70]
in light of the time pressure regarding the [research paper](https://github.com/capstone-coal/pycoal/issues/27) and the rest of the work all of us have to do, i thought it would be pertinent to file [this issue](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker's_Guide_to_the_Galaxy#Don.27t_Panic) which has been on my to-do list for a while.

**Comment by lewismc** [comment]
lol

**Comment by ghost** [comment]
@lewismc @heidiaclayton @xiaomei7 sorry for losing my cool. this is what it must feel like when your space probe is careening towards a planet and you only have a couple days to avert a collision.

**Comment by lewismc** [comment]
No problem @browtayl no offense taken and none meant.
