### ISSUE TITLE
Consider Using Interview

### ISSUE THREAD

**Issue by ghost** [capstone-coal/pycoal#90]
The [COAL review interview](https://groups.google.com/forum/#!topic/coal-capstone/MpNIhaXzl1s) I posted to the mailing list is a potential resource for adding frequently asked questions or less technical language to our project. This issue is simply to consider whether to do anything with these or similar materials.

**Comment by ghost** [comment]
Unassigning self as I'm not working on this right now. Some kind of FAQ or non-technical description would be useful, so feel free to repurpose my responses in that interview. I could contact my classmate for permission if it is desired to use the interview in full, but I think it's probably too long for a non-technical reader.

**Comment by lewismc** [comment]
We can use the interview as a use case gathering later in, thank you again for recording this Taylor.
